# Use the official Node.js image as the base image
FROM node:latest

# Create and set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all backend files to the working directory
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Define the command to start your application
CMD ["node", "index.js"]
